name: Build All Examples

on:
  pull_request:
    types: [labeled, synchronize]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        type: environment
        required: false

jobs:
  chunks:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-build-examples
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Create Example Chunks

    outputs:
      CHUNK_1: ${{ steps.chunkstep.outputs.CHUNK_1 }}
      CHUNK_2: ${{ steps.chunkstep.outputs.CHUNK_2 }}
      CHUNK_3: ${{ steps.chunkstep.outputs.CHUNK_3 }}
      CHUNK_4: ${{ steps.chunkstep.outputs.CHUNK_4 }}
      CHUNK_5: ${{ steps.chunkstep.outputs.CHUNK_5 }}
      CHUNK_6: ${{ steps.chunkstep.outputs.CHUNK_6 }}
      CHUNK_7: ${{ steps.chunkstep.outputs.CHUNK_7 }}
      CHUNK_8: ${{ steps.chunkstep.outputs.CHUNK_8 }}

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      # run npm ci
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Split Into Chunks
        id: chunkstep
        run: CHUNKS=8 node ./.github/workflows/build-example-chunks.js
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && contains(steps.pr-labels.outputs.labels, ' build-examples '))

  build-chunk-1:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_1 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-1
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 1)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_1 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_1 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-2:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_2 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-2
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 2)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_2 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_2 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-3:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_3 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-3
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 3)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_3 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_3 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-4:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_4 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-4
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 4)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_4 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_4 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-5:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_5 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-5
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 5)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_5 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_5 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-6:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_6 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-6
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 6)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_6 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_6 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-7:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_7 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-7
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 7)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_7 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_7 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

  build-chunk-8:
    runs-on: ubuntu-latest
    if: "${{ needs.chunks.outputs.CHUNK_8 != '' }}"
    concurrency:
      group: ${{ github.ref }}-build-examples-chunk-8
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Build All Examples (Chunk 8)

    needs: chunks

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap -- --scope={${{ needs.chunks.outputs.CHUNK_8 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria

      - name: Build
        run: npm run build -- --no-bail --scope={${{ needs.chunks.outputs.CHUNK_8 }}} --ignore blog-sveltekit-crud --ignore blog-react-aria
