name: stable Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-stable-release
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run bootstrap:all
          npm run build:all
      #- name: Lint
      #  run: npm run lint
      - name: Test
        run: npm run test:all
      - name: Prepare Stable version changesets
        if: "!contains(github.event.head_commit.message, 'ci(changesets): version packages')"
        run: |
          cp -R ./_changeset/* ./.changeset || : && rm -rf ./_changeset/
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run changeset version
          publish: npm run changeset publish
          commit: "ci(changesets): version packages"
          title: "ci(changesets): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.PANKOD_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: update master branch
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: |
          git config --global user.email "bot@pankod.com"
          git config --global user.name "pankod-bot"
          git checkout master
          git pull origin master
          rm -rf ./_changeset/
          git commit -am "chore: remove deployed changesets ci skip"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PANKOD_BOT_TOKEN }}
      - name: update next branch
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: |
          git config --global user.email "bot@pankod.com"
          git config --global user.name "pankod-bot"
          git fetch origin
          git checkout next
          git pull origin next
          rm -rf ./_changeset/
          git commit -am "chore: remove deployed changesets ci skip"
          git push origin next
        env:
          GITHUB_TOKEN: ${{ secrets.PANKOD_BOT_TOKEN }}
  documentation-gh:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-stable-documentation
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Build packages
        run: |
          npm ci
          npm run bootstrap:all
          npm run build:all
          cd documentation
          npm ci
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: pankod-bot
          NODE_ENV: production
        run: |
          cd documentation
          git config --global user.email "bot@pankod.com"
          git config --global user.name "pankod-bot"
          LIVE_PREVIEW_URL=https://next.live-previews.refine.dev/preview npm run deploy
